iso_parameters = {'metric' : {'Action' : 'Load',
                                  'ID' : 'C7732185',
                                  'Type' : None,
                                  'Digits' : '5',
                                  'P' : None,
                                  'TLow' : None,
                                  'THigh' : None,
                                  'TInc' : None,
                                  'RefState' : 'DEF',
                                  'TUnit' : 'K',
                                  'PUnit' : 'bar',
                                  'DUnit' : 'kg%2Fm3',
                                  'HUnit' : 'kJ%2Fkg',
                                  'WUnit' : 'm%2Fs',
                                  'VisUnit' : 'uPa*s',
                                  'STUnit' : 'N%2Fm'},
                   'imperial' : {'Action' : 'Load',
                                  'ID' : 'C7732185',
                                  'Type' : None,
                                  'Digits' : '5',
                                  'P' : None,
                                  'TLow' : None,
                                  'THigh' : None,
                                  'TInc' : None,
                                  'RefState' : 'DEF',
                                  'TUnit' : 'K',
                                  'PUnit' : 'bar',
                                  'DUnit' : 'kg%2Fm3',
                                  'HUnit' : 'kJ%2Fkg',
                                  'WUnit' : 'm%2Fs',
                                  'VisUnit' : 'uPa*s',
                                  'STUnit' : 'N%2Fm'}
                   }

sat_parameters = {'metric' : {'Action' : 'Load',
                              'ID' : 'C7732185',
                              'Type' : 'SatT',
                              'Digits' : 5,
                              'PLow' : 2,
                              'PHigh' : 28,
                              'PInc' : 2,
                              'RefState' : 'DEF',
                              'TUnit' : 'F',
                              'PUnit' : 'psia',
                              'DUnit' : 'lbm%2Fft3',
                              'HUnit' : 'Btu%2Flbm',
                              'WUnit' : 'ft%2Fs',
                              'VisUnit' : 'lbm%2Fft*s',
                              'STUnit' : 'lb%2Fft'},
                  }

acceptable_ranges = {'metric' : {'Tmin' : 273.16,
                                 'Tmax' : 1275.0,
                                 'TSmin' : 273.16,
                                 'TSmax' : 647.096,
                                 'Pmin' : 0,
                                 'Pmax' : 10000.0,
                                 'PSmin' : .006125,
                                 'PSmax' : 220.64},
                     'imperial' : {'Tmin' : 32.02,
                                   'Tmax' : 1835.3,
                                   'TSmin' : 32.02,
                                   'TSmax' : 705.103,
                                   'Pmin' : 0,
                                   'Pmax' : 145037.74,
                                   'PSmin' : .088833,
                                   'PSmax' : 3200.11}
                     }

'Action=Load&ID=C7732185&Type=SatT&Digits=5&PLow=02&PHigh=28&PInc=2&RefState=DEF&TUnit=F&PUnit=psia&DUnit=lbm%2Fft3&HUnit=Btu%2Flbm&WUnit=ft%2Fs&VisUnit=lbm%2Fft*s&STUnit=lb%2Fft'